[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.copy-binary]
script = "doas install -s -Dm755 ./target/release/tl /usr/bin/tl"

[tasks.install]
dependencies = [
  "clean",
  "build",
  "copy-binary"
]

[tasks.update]
dependencies = [
  "clean",
  "build",
  "copy-binary"
]
